steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Spark
    waitFor: ['-']
    timeout: 600s
    args:
      - build
      - -t
      - gcr.io/hybrid-qubole/spark:$BRANCH_NAME
      - spark/
  - name: 'gcr.io/cloud-builders/docker'
    id: SparkPush
    timeout: 300s
    waitFor:
      - Spark
    args:
      - push
      - gcr.io/hybrid-qubole/spark:$BRANCH_NAME
  - name: 'gcr.io/cloud-builders/docker'
    id: SparkPy36
    waitFor:
      - Spark
      - SparkPush
    timeout: 600s
    args:
      - build
      - --build-arg
      - BASE_CONTAINER=gcr.io/hybrid-qubole/spark:$BRANCH_NAME
      - -t
      - gcr.io/hybrid-qubole/spark-python:3.6-$BRANCH_NAME
      - spark/python-3.6/
timeout: 2400s
tags:
  - $BRANCH_NAME
  - 3.6-$BRANCH_NAME
images:
  - gcr.io/hybrid-qubole/spark
  - gcr.io/hybrid-qubole/spark-python