steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: HiveMetastore
    timeout: 600s
    args:
      - build
      - -t
      - gcr.io/hybrid-qubole/hive-metastore:latest
      - hive-metastore/
  - name: 'gcr.io/cloud-builders/docker'
    id: JupyterPySpark
    timeout: 1200s
    waitFor: ['-']
    args:
      - build
      - -t
      - gcr.io/hybrid-qubole/jupyter-pyspark:latest
      - jupyter/pyspark/
  - name: 'gcr.io/cloud-builders/docker'
    id: Jupyter
    waitFor:
      - JupyterPySpark
    timeout: 1200s
    args:
      - build
      - --build-arg
      - BASE_CONTAINER=gcr.io/hybrid-qubole/jupyter-pyspark:latest
      - -t
      - gcr.io/hybrid-qubole/jupyter:latest
      - jupyter/
  - name: 'gcr.io/cloud-builders/docker'
    id: Spark
    waitFor: ['-']
    timeout: 600s
    args:
      - build
      - -t
      - gcr.io/hybrid-qubole/spark:latest
      - spark/
  - name: 'gcr.io/cloud-builders/docker'
    id: SparkPy36
    waitFor:
      - Spark
    timeout: 600s
    args:
      - build
      - --build-arg
      - BASE_CONTAINER=gcr.io/hybrid-qubole/spark:latest
      - -t
      - gcr.io/hybrid-qubole/spark-python:3.6-latest
      - spark/python-3.6/
timeout: 2400s
tags:
  - latest
  - $COMMIT_SHA
  - 3.6-latest
images:
  - gcr.io/hybrid-qubole/hive-metastore
  - gcr.io/hybrid-qubole/jupyter-pyspark
  - gcr.io/hybrid-qubole/jupyter
  - gcr.io/hybrid-qubole/spark
  - gcr.io/hybrid-qubole/spark-python