steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: HiveMetastore
    timeout: 600s
    args:
    - build
    - -t
    - gcr.io/hybrid-qubole/hive-metastore:$BRANCH_NAME
    - hive-metastore/
  - name: 'gcr.io/cloud-builders/docker'
    id: JupyterPySpark
    timeout: 1200s
    args:
      - build
      - -t
      - gcr.io/hybrid-qubole/jupyter-pyspark:$BRANCH_NAME
      - jupyter/pyspark/
  - name: 'gcr.io/cloud-builders/docker'
    id: Jupyter
    waitFor:
      - JupyterPySpark
    timeout: 1200s
    args:
      - build
      - --build-arg
      - BASE_CONTAINER=gcr.io/hybrid-qubole/jupyter-pyspark:$BRANCH_NAME
      - -t
      - gcr.io/hybrid-qubole/jupyter-pyspark:$BRANCH_NAME
      - jupyter/
timeout: 3000s
tags:
  - $BRANCH_NAME
  - $COMMIT_SHA
images:
  - gcr.io/hybrid-qubole/hive-metastore
  - gcr.io/hybrid-qubole/jupyter-pyspark
  - gcr.io/hybrid-qubole/jupyter