steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: HiveMetastore
    timeout: 600s
    args:
    - build
    - -t
    - gcr.io/hybrid-qubole/hive-metastore:$BRANCH_NAME
    - hive-metastore/
timeout: 2400s
tags:
  - $BRANCH_NAME
  - $COMMIT_SHA
images:
  - gcr.io/hybrid-qubole/hive-metastore
