apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-config
  labels:
    app: hive-metastore
data:
  DB_TPYE: "mysql"
  CONNECTION_URI: jdbc:mysql://metastore-mysql:3306/metastore
  CONNECTION_USER: hive
  CONNECTION_PASSWORD: password
  CONNECTION_DRIVER: "com.mysql.jdbc.Driver"
  AWS_ACCESS_KEY_ID: <ACCESS KEY ID>
  AWS_SECRET_ACCESS_KEY: <SECRET ACCESS KEY>