apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
spec:
  selector:
    matchLabels:
      app: hive-metastore
  replicas: 1
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: quay.io/chattarajoy/hive-metastore:latest
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          resources:
            limits:
              cpu: 0.8
              memory: 800Mi
            requests:
              cpu: 0.2
              memory: 200Mi
          ports:
            - containerPort: 9083
          envFrom:
            - configMapRef:
                name: hive-metastore-config

