apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
spec:
  type: ClusterIP
  ports:
    - name: thrift
      port: 9083
      protocol: TCP
  selector:
    app: hive-metastore